pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            agent any
            steps {
                git branch: 'feature/allure-test-report',
                url: 'https://github.com/bridgeshi85/playwright-pytest-allure-framework'
            }
        }

        stage('Run UI Tests (Playwright Agent)') {
            agent {
                docker {
                    image 'playwright-test-agent:latest'
                    args '--network e2e-test'
                    reuseNode true     // 复用同一个workspace
                }
            }
            steps {
                sh '''
                    set -euxo pipefail
                    echo "Running tests..."
                    cd playwright-automation-test
                    pytest tests/test_login.py --env=jenkins -s
                '''
            }
        }
    }
    
    
    post {
        always {
            allure(
                includeProperties: false,
                jdk: '',
                resultPolicy: 'LEAVE_AS_IS',
                results: [[path: 'playwright-automation-test/reports/allure-results']]
            )
            
            emailext(
                subject: "[${env.JOB_NAME}] Build #${env.BUILD_NUMBER} - ${currentBuild.currentResult}",
                to: "bridgeshi93@gmail.com",
                mimeType: 'text/html',
                body: """
                    <p><b>Build Status:</b> ${currentBuild.currentResult}</p>
                    <p><b>Job:</b> ${env.JOB_NAME}</p>
                    <p><b>Build Number:</b> ${env.BUILD_NUMBER}</p>
                    <p><b>Build URL:</b>
                       <a href="${env.BUILD_URL}">${env.BUILD_URL}</a>
                    </p>
                    <p><b>Allure Report:</b>
                       <a href="${env.BUILD_URL}allure/">View Report</a>
                    </p>
                """
            )
        }
    }
}